apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: visists-app
          image: pandaemoniumplaza/docker-practice
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: app-redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
